version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: medical_appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/media:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:password@db:5432/medical_appointment_db
      - REDIS_URL=redis://redis:6379

volumes:
  postgres_data:
